lr: 2e-4
gamma: 0.9
state_dim: [128, 128]
device: cuda:0
num_episodes: 100
eps_train: 0.2
clip_value: 0.1
survive_time: 10
terminate_on_death: True
# 2 - Left, Right
# 3 - Left, Right, Stay
# 5 - Left, Right, Stay, Up, Down
# 9 - Full no shift
# 17 - Full with shift
num_actions: 2
num_bullets_spawn: 6
bullets_speed: 5
random: False