lr: 1e-3
gamma: 0.3
state_dim: [128, 128]
device: cuda:0
num_episodes: 100
# Eps-greedy
eps_initial: 0.1
eps_final: 0.1
eps_decay: 0.9
clip_value: 0.1
survive_time: 10
terminate_on_death: False
# 2 - Left, Right
# 3 - Left, Right, Stay
# 5 - Left, Right, Stay, Up, Down
# 9 - Full no shift
# 17 - Full with shift
num_actions: 5
# Always hold shift for precise movement (if num_actions <= 9)
hold_shift: True
num_bullets_spawn: 8
bullets_speed: 5
random: True
survive_reward: 1
death_reward: -50
frame_step: 4