lr: 5e-4
gamma: 0.8
state_dim: [120, 120]
device: cuda:0
num_episodes: 100
eps_train: 0.2
clip_value: 0.1
survive_time: 20
terminate_on_death: False
# 2 - Left, Right
# 3 - Left, Right, Stay
# 5 - Left, Right, Stay, Up, Down
# 9 - Full no shift
# 17 - Full with shift
num_actions: 2